model:
  model_type: music-transformer
  params:
    n_vocab: 137 # wielkość słownika tokenów
    n_ctx: 1955 # maksymalna długość sekwencji (konkretne zależne od danych)
    n_embd: 600 # wymiar wektora osadzeń
    n_head: 12 # liczba głów uwagi
    n_layer: 12 # liczba bloków transformerowych
    lr: 0.002
    lr_decay: 0.97
    lr_decay_start: 20

dataloaders:
  validation:
    name: "folk-rnn"
    root: "_data"
    split: "test"
    download: True
    data_type: "tokenized_ABC"

    transforms:
      - folk_rnn:

    batch_size: 16
    num_workers: 4
    collate_fn: "pad_collate_single_sequence"

  train:
    - dataset:
        name: "folk-rnn"
        root: "_data"
        split: "train"
        download: True
        data_type: "tokenized_ABC"
        transforms:
          - folk_rnn:

        batch_size: 4
        num_workers: 4
        collate_fn: "pad_collate_single_sequence"

lightning:
  trainer:
    benchmark: True
    max_epochs: 150
    accumulate_grad_batches: 128

callbacks:
  - model_checkpoint:
      filename: "{epoch:06}"
      verbose: True
      save_last: True
  - checkpoint_every_n_steps:
      save_step_frequency: 1000
      prefix: "N-Step-Checkpoint"
      use_modelcheckpoint_filename: False
  - setup_callback:
