model:
  model_type: performance-rnn
  output_transforms:
    - tensor_to_toksequence:
    - midi_tokenizer_inv:
        tokenizer_params:
          tokenization: midilike
          pitch_range: [0, 127]
          vocab_size: 413 
          special_tokens: []
          max_duration:  [1, 125, 125] # num_beats, num_frames, res_frames
          note_on_count: 128
          note_off_count: 128
          num_velocities: 32 
  params:
    vocab_size: 137
    num_layers: 3
    lstm_size: 512
    dropout: 0.5
    lr: 0.002
    lr_decay: 0.97
    lr_decay_start: 20

dataloaders:
  validation:
    name: "folk-rnn"
    root: "_data"
    split: "test"
    download: True
    data_type: "tokenized_ABC"
    transforms:
      - split_lines:
      - abc_midi:
      - midi_tokenizer:
          tokenizer_params:
            tokenization: midilike
            pitch_range: [0, 127]
            vocab_size: 413 
            special_tokens: []
            max_duration:  [1, 125, 125] # num_beats, num_frames, res_frames
            note_on_count: 128
            note_off_count: 128
            num_velocities: 32
    batch_size: 32
    num_workers: 4
    collate_fn: "pad_collate_single_sequence"

  train:
    - dataset:
        name: "folk-rnn"
        root: "_data"
        split: "train"
        download: False
        data_type: "tokenized_ABC"
        transforms:
          - split_lines:
          - abc_midi:
          - midi_tokenizer:
              tokenizer_params:
                tokenization: midilike
                pitch_range: [0, 127]
                vocab_size: 413 
                special_tokens: []
                max_duration:  [1, 125, 125] # num_beats, num_frames, res_frames
                note_on_count: 128
                note_off_count: 128
                num_velocities: 32

        batch_size: 32
        num_workers: 4
        collate_fn: "pad_collate_single_sequence"

lightning:
  trainer:
    benchmark: True
    max_epochs: 100
    gradient_clip_algorithm: "value"
    gradient_clip_val: 5

callbacks:
  - model_checkpoint:
      filename: "{epoch:06}"
      verbose: True
      save_last: True
  - checkpoint_every_n_steps:
      save_step_frequency: 1000
      prefix: "N-Step-Checkpoint"
      use_modelcheckpoint_filename: False
  - setup_callback:
  - cuda_callback:
    #- frechet_music_distance:
    # every_n_epochs: 5
    # batch_size: 64
    # dataset_path: "_data/train/folk_rnn/"
